application: homeawesomation
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: appengine.main.app
  secure: always

- url: /tasks/update
  script: appengine.main.app
  login: admin

libraries:
- name: webapp2
  version: latest
